.deploy_redis_template:
  stage: redis
  image:
    name: petrahub.petra.ac.id/eksternal/bitnami-kubectl
    entrypoint: [""]
  variables:
    DEPLOYMENT_FILE: redis.yaml
  before_script:
    - if [[ "$CI_COMMIT_TAG" =~ v[0-9].+ ]]; then IMAGE_REGISTRY_TAG=$CI_COMMIT_TAG; fi
    - sed -i "s/\${NAMESPACE}/$NAMESPACE/g" $DEPLOYMENT_DIR/*.yaml
    - CLEAN_PROJECT_NAME=$(echo "$CI_PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | tr -s '-' | sed 's/^-//; s/-$//')
    - sed -i "s/\${CI_PROJECT_NAME}/$CLEAN_PROJECT_NAME/g" $DEPLOYMENT_DIR/*.yaml
  script:
    - get_var() { local target_var="${1}_${ENV_SUFFIX}"; echo "${!target_var}"; }
    - echo -n $(get_var KUBE_CONFIG) | base64 -d > $KUBECONFIG
    - kubectl apply -f $DEPLOYMENT_DIR/$DEPLOYMENT_FILE -n $NAMESPACE

.deploy_image_template:
  stage: deploy
  image:
    name: petrahub.petra.ac.id/eksternal/bitnami-kubectl
    entrypoint: [""]
  variables:
    DEPLOYMENT_FILE: deployment.yaml
  before_script:
    - get_var() { local target_var="${1}_${ENV_SUFFIX}"; echo "${!target_var}"; }
    - if [[ "$CI_COMMIT_TAG" =~ v[0-9].+ ]]; then IMAGE_REGISTRY_TAG=$CI_COMMIT_TAG; fi
    - CLEAN_PROJECT_NAME=$(echo "$CI_PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | tr -s '-' | sed 's/^-//; s/-$//')
    - sed -i "s/\${CI_PROJECT_NAME}/$CLEAN_PROJECT_NAME/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${IMAGE_REGISTRY}/$IMAGE_REGISTRY/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${NAMESPACE}/$NAMESPACE/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${PROJECT_GROUP}/$PROJECT_GROUP/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${IMAGE_REGISTRY_TAG}/$IMAGE_REGISTRY_TAG/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${CI_PROJECT_TITLE}/$CI_PROJECT_TITLE/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${INGRESS_URL}/$(get_var INGRESS_URL)/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${CI_COMMIT_BRANCH}/$CI_COMMIT_BRANCH/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${CI_COMMIT_SHORT_SHA}/$CI_COMMIT_SHORT_SHA/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${CI_JOB_ID}/$CI_JOB_ID/g" $DEPLOYMENT_DIR/*.yaml
  script:
    - get_var() { local target_var="${1}_${ENV_SUFFIX}"; echo "${!target_var}"; }
    - echo -n $(get_var KUBE_CONFIG) | base64 -d > $KUBECONFIG
    - echo $IMAGE_REGISTRY/$PROJECT_GROUP/$NAMESPACE/$CI_PROJECT_NAME:$IMAGE_REGISTRY_TAG
    - kubectl apply -f $DEPLOYMENT_DIR/$DEPLOYMENT_FILE -n $NAMESPACE

.deploy_hpa_template:
  stage: hpa
  image:
    name: petrahub.petra.ac.id/eksternal/bitnami-kubectl
    entrypoint: [""]
  variables:
    HPA_FILE: hpa.yaml
  before_script:
    - sed -i "s/\${NAMESPACE}/$NAMESPACE/g" $DEPLOYMENT_DIR/*.yaml
    - CLEAN_PROJECT_NAME=$(echo "$CI_PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | tr -s '-' | sed 's/^-//; s/-$//')
    - sed -i "s/\${CI_PROJECT_NAME}/$CLEAN_PROJECT_NAME/g" $DEPLOYMENT_DIR/*.yaml
  script:
    - get_var() { local target_var="${1}_${ENV_SUFFIX}"; echo "${!target_var}"; }
    - echo -n $(get_var KUBE_CONFIG) | base64 -d > $KUBECONFIG
    - kubectl apply -f $DEPLOYMENT_DIR/$HPA_FILE -n $NAMESPACE

.deploy_service_template:
  stage: service
  image:
    name: petrahub.petra.ac.id/eksternal/bitnami-kubectl
    entrypoint: [""]
  variables:
    SERVICE_FILE: service.yaml
  before_script:
    - sed -i "s/\${NAMESPACE}/$NAMESPACE/g" $DEPLOYMENT_DIR/*.yaml
    - CLEAN_PROJECT_NAME=$(echo "$CI_PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | tr -s '-' | sed 's/^-//; s/-$//')
    - sed -i "s/\${CI_PROJECT_NAME}/$CLEAN_PROJECT_NAME/g" $DEPLOYMENT_DIR/*.yaml
  script:
    - get_var() { local target_var="${1}_${ENV_SUFFIX}"; echo "${!target_var}"; }
    - echo -n $(get_var KUBE_CONFIG) | base64 -d > $KUBECONFIG
    - kubectl apply -f $DEPLOYMENT_DIR/$SERVICE_FILE -n $NAMESPACE

.deploy_ingress_template:
  stage: ingress
  image:
    name: petrahub.petra.ac.id/eksternal/bitnami-kubectl
    entrypoint: [""]
  variables:
    INGRESS_FILE: ingress.yaml
  before_script:
    - sed -i "s/\${NAMESPACE}/$NAMESPACE/g" $DEPLOYMENT_DIR/*.yaml
    - CLEAN_PROJECT_NAME=$(echo "$CI_PROJECT_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | tr -s '-' | sed 's/^-//; s/-$//')
    - sed -i "s/\${CI_PROJECT_NAME}/$CLEAN_PROJECT_NAME/g" $DEPLOYMENT_DIR/*.yaml
    - sed -i "s/\${INGRESS_URL}/$INGRESS_URL/g" $DEPLOYMENT_DIR/*.yaml
  script:
    - get_var() { local target_var="${1}_${ENV_SUFFIX}"; echo "${!target_var}"; }
    - echo -n $(get_var KUBE_CONFIG) | base64 -d > $KUBECONFIG
    - kubectl apply -f $DEPLOYMENT_DIR/traefik.yaml -n $NAMESPACE
    - kubectl apply -f $DEPLOYMENT_DIR/$INGRESS_FILE -n $NAMESPACE
